train_dir: 'data/train'
test_dir: 'data/test'

train_on: 'ensemble' #'efficientnet' #'incep_resnet' #'ensemble'
log_dir: 'logs'
save_model_dir: 'saved_models'
tensorboard_dir: 'tensorboard'
efficientnet_model: 'saved_models/efficientnet.h5'
incep_res_model: 'saved_models/incep_res.h5'
ensemble_model: 'saved_models/ensemble.h5'
pretrain: False

infer_dir: 'data/single_test'

batch_size: 4
epochs: 100
no_of_classes: 4